# Generated by Django 4.0.4 on 2022-04-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_role',
            field=models.CharField(choices=[('Подписчик', 'Подписчик'), ('Автор', 'Автор')], max_length=10),
        ),
    ]
