# Generated by Django 4.0.4 on 2022-04-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='reader_role',
            field=models.CharField(choices=[('follower', 'follower'), ('all', 'all')], max_length=10, verbose_name='Роль читателя'),
        ),
    ]
